---
# tasks file for webserver
- include: create_user.yml
- name: Install epel from remote repo on CentOS 6
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
  when: ansible_distribution_major_version == "6"
- name: Install epel from remote repo on CentOS 7
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution_major_version == "7"
- name: Install webstatic on CentOS 6
  yum: name=https://mirror.webtatic.com/yum/el6/latest.rpm state=present
  when: ansible_distribution_major_version == "6"
- name: Install webstatic on CentOS 7
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present
  when: ansible_distribution_major_version == "7"
- include: nginx-centos.yml
# Install PHP7 packages.
- name: Install PHP Packages
  yum: name={{ item }} state=present
  with_nested: "{{ yum_php_packages }}"
  when: yum_php_packages is defined
  notify: restart php7-fpm on centos
- include: php-fpm-centos.yml
